sudo: required
language: node_js
node_js:
  - "10.8"
cache:
  directories:
    - "node_modules"
services:
  - docker
before_install:
  - sudo service postgresql stop
  - docker-compose -f prisma/docker-compose.yml up -d
  - sleep 20
  - docker ps
before_script:
  - npm install -g prisma
  - cd prisma && prisma deploy
  - curl -I http://localhost:4466/travisci/test