sudo: required
language: node_js
node_js:
  - "iojs"
cache:
  directories:
    - "node_modules"
services:
  - docker
before_install:
  - docker-compose -f prisma/docker-compose-yml up -d
  - docker ps
  - sleep 20
before_script:
  - yarn prisma deploy